export const cameroonCities = [
  'Douala',
  'Yaoundé',
  'Bafoussam',
  'Bamenda',
  'Kribi',
  'Limbe',
  'Buea',
  'Garoua',
  'Maroua',
  'Ngaoundéré',
  'Bertoua',
  'Ebolowa',
  'Dschang',
  'Kumba',
  'Nkongsamba',
];

export const mockOffers = [
  {
    id: '1',
    from: 'Douala',
    to: 'Yaoundé',
    image: 'https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?w=400',
    discount: '-20%',
    price: '5 000 FCFA',
  },
  {
    id: '2',
    from: 'Yaoundé',
    to: 'Bafoussam',
    image: 'https://images.unsplash.com/photo-1596005554384-d293674c91d7?w=400',
    discount: null,
    price: '4 500 FCFA',
  },
  {
    id: '3',
    from: 'Douala',
    to: 'Kribi',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400',
    discount: '-15%',
    price: '3 000 FCFA',
  },
  {
    id: '4',
    from: 'Douala',
    to: 'Bamenda',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400',
    discount: null,
    price: '6 000 FCFA',
  },
];

export const mockTrips = [
  {
    id: '1',
    company: 'Général Express',
    companyColor: '#E53E3E',
    departureTime: '06:00',
    arrivalTime: '09:30',
    duration: '3h 30m',
    type: 'Direct',
    price: '5 000 FCFA',
    priceValue: 5000,
    features: ['Climatisé', '1 Bagage'],
    seatsLeft: null,
  },
  {
    id: '2',
    company: 'Touristique Express',
    companyColor: '#3182CE',
    departureTime: '08:00',
    arrivalTime: '11:45',
    duration: '3h 45m',
    type: 'Direct',
    price: '5 500 FCFA',
    priceValue: 5500,
    features: ['Climatisé', 'WC'],
    seatsLeft: 5,
  },
  {
    id: '3',
    company: 'Buca Voyages',
    companyColor: '#38A169',
    departureTime: '13:00',
    arrivalTime: '17:30',
    duration: '4h 30m',
    type: '1 Arrêt',
    price: '4 500 FCFA',
    priceValue: 4500,
    features: ['Climatisé'],
    seatsLeft: null,
  },
];

export const mockSeats = [
  { id: '1A', status: 'free' },
  { id: '1B', status: 'free' },
  { id: '1C', status: 'occupied' },
  { id: '1D', status: 'free' },
  { id: '2A', status: 'free' },
  { id: '2B', status: 'occupied' },
  { id: '2C', status: 'free' },
  { id: '2D', status: 'occupied' },
  { id: '3A', status: 'free' },
  { id: '3B', status: 'free' },
  { id: '3C', status: 'free' },
  { id: '3D', status: 'free' },
  { id: '4A', status: 'free' },
  { id: '4B', status: 'free' },
  { id: '4C', status: 'free' },
  { id: '4D', status: 'free' },
  { id: '5A', status: 'free' },
  { id: '5B', status: 'occupied' },
  { id: '5C', status: 'occupied' },
  { id: '5D', status: 'free' },
  { id: '6A', status: 'free' },
  { id: '6B', status: 'occupied' },
  { id: '6C', status: 'free' },
  { id: '6D', status: 'free' },
];

export const mockTickets = {
  upcoming: [
    {
      id: 'TR88392',
      status: 'CONFIRMÉ',
      statusColor: '#22c55e',
      from: 'Douala',
      to: 'Yaoundé',
      departureTime: '06:00',
      arrivalTime: '09:30',
      duration: '3h 30m',
      date: 'Ven 14 Juin, 2026',
      seat: '12A',
    },
  ],
  pending: [
    {
      id: 'TR99481',
      status: 'EN ATTENTE',
      statusColor: '#f59e0b',
      from: 'Yaoundé',
      to: 'Bafoussam',
      date: 'Sam 21 Juin',
      time: '08:00',
    },
  ],
};

export const mockInvoice = {
  invoiceNumber: 'INV-839210',
  date: 'Le 14 Juin 2026 à 06:00',
  route: 'Douala → Yaoundé',
  passenger: 'Thomas Ndongo',
  paymentMethod: 'Mobile Money •••• 7890',
  items: [
    { label: 'Billet Standard (x1)', price: '5 000 FCFA' },
    { label: 'Siège Fenêtre', price: '500 FCFA' },
    { label: 'Assurance voyage', price: '200 FCFA' },
  ],
  total: '5 700 FCFA',
};

export const mockUser = {
  firstName: 'Thomas',
  lastName: 'Ndongo',
  email: 'thomas.ndongo@email.com',
  phone: '+237 6 99 12 34 56',
  birthDate: '15/06/1995',
  gender: 'Homme',
  badge: 'Voyageur Gold',
  avatar: null,
  referralCode: 'YENDI23',
};
